### PR TITLE
Fix error formatting

### PR DESCRIPTION
**Pull request by bencehornak**
As @jmbldwn pointed out in #11, errors are not rendered correctly, due to some changes of a dependency.

This is also indicated by the failing test:
```
  1) log4js-json-layout should format stack traces:
     AssertionError: expected '{"startTime":"615 Ludlam Place, Nicholson, New Mexico, 5763","categoryName":"572efdaaa64be9dbc56369ae","level":"INFO","data":"{ inspect: [Function: inspect] }"}' to include '"data":"Error: Whoops!\\n    at Context.<anonymous>'
      at Context.<anonymous> (test/unit/lib/jsonLayout.js:68:19)
      at processImmediate (internal/timers.js:461:21)
```

A simple fix is that fixed the tests was simply returning the error object, instead of the `{inspect() {...}}` construct.

### CODE REVIEW

**Review by jmbldwn — APPROVED** [review]
This looks like it would work.  I'm not sure what `inspect()` was supposed to do...

**Comment by id0Sch** [comment]
Hi :)
Sorry, I was unavailable, I'm swamped at work and have little to no time to maintain this lib.

I really appreciate you guys taking the time to discuss and suggest a fix, @jmbldwn please let me know once you made sure this fixes your issue so I can merge and release a new version (feels like a patch IMO).

Thanks again!!

**Comment by bencehornak** [comment]
No worries @id0Sch, thanks for the lib!

Yes, it sounds like a patch version.

**Comment by jmbldwn** [comment]
I checked out this PR and can confirm the tests pass now, but I ended up working around this problem a few weeks ago so not easy for me to test whether it fixes my original issue.

On Apr 12, 2021, at 8:01 AM, Bence Hornák ***@***.******@***.***>> wrote:



No worries @id0Sch<https://github.com/id0Sch>, thanks for the lib!

Yes, it sounds like a patch version.

**Comment by id0Sch** [comment]
published 2.2.3

**Pull request merged**
